version: 0.0
os: linux
files:
 - source: /Projeto/
   destination: /home/ubuntu/Projeto
 - source: requirements.txt
   destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: scripts/dependencias
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root