version: 0.0
os: linux
files:
 - source: /Projeto/
   destination: /home/ubuntu/Projeto
 - source: requeriments.txt
   destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: scripts/dependencias.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root